apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system
  namespace: solar-system # This is the namespace where the deployment will be created
  labels:
    app: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: soar-system
        image: venkateshkesa/solar-system:v2
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
