apiVersion: v1
kind: Service
metadata:
  name: solar-system-service
  namespace: solar-system
spec:
  selector:
    app: solar-system
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

# The service.yaml file is used to create a service in the Kubernetes cluster. The service is used to expose the deployment to the outside world. The service is created in the same namespace as the deployment. The service is of type LoadBalancer, which means that the service will be exposed to the outside world. The service will be exposed on port 80, and it will forward the traffic to port 3000 of the deployment. The service will forward the traffic to the deployment based on the label app: solar-system. The service will be created in the same namespace as the deployment. The service will be named solar-system-service
